# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
# orgs contain basc recipes and reproducible actions (install node, aws, eb and browser)
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
  browser: circleci/browser-tools@1.2.4
# Define a job to be invoked
jobs:
  build:
    docker:
    # the base image can run most needed actions with orbs
      - image: cimg/node:16.13.2
    # Add steps to the job
    steps:
      - browser/install-chrome
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      # install the dependencies of the front end app
      - run:
          name: Front-End Install 
          command: |
            npm run install-frontend
      # install the dependencies of the back end app
      - run:
          name: Back-End Install
          command: |
            npm run install-backend
      # build the front end app before deploying it
      - run: 
          name: Front-End Build
          command: |
            npm run build-frontend
      # build the back end app before deploying it
      - run:
          name: Back-End Build
          command: |
            npm run build-backend
      # deploy the front end app to aws bucket
      - run:
          name: Front-End Deploy
          command: |
            npm run deploy-frontend
      # deploy the back end app to aws elastic beanstalk
      - run:
          name: Back-End Deploy
          command: |
            npm run deploy-backend
